pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/Flukena/project-sw-dev-and-env.git'
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd project_dev-tools_frontend && npm install && npm install axios'
            }
        }
        stage('Unit test') {
            steps {
                sh 'cd project_dev-tools_frontend && npm run test'
            }
        }
        stage('Component test') {
            steps {
                echo 'npm run component test'
            }
        }
        stage('E2E test') {
            steps {
                echo 'npm run e2e test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
}
