pipeline {
    agent any

    stages {
//         stage('Pull code') {
//             steps {
//                 git branch: 'main', url: 'https://github.com/Flukena/project-sw-dev-and-env.git'
//             }
//         }
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd project_dev-tools_server && npm install'
            }
        }
        stage('Unit test') {
            steps {
                dir('./project_dev-tools_server') {
                    sh 'npm run test'

                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage/lcov-report",
                        reportFiles: "index.html",
                        reportName: 'Coverage Unit Test Report'
                ]
                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage",
                        reportFiles: "report.html",
                        reportName: 'Unit Test Report'
                ]
                }
            }
        }
        
        stage('Component test') {
            steps {
                dir('./project_dev-tools_server') {
                    echo 'npm run test 12'
                }
            }
        }
        
        stage("Code coverage report") {
            steps {
                clover(cloverReportDir: 'project_dev-tools_server/coverage', cloverReportFileName: 'clover.xml',
                    healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                    unhealthyTarget: [methodCoverage: 40, conditionalCoverage: 50, statementCoverage: 50],
                    failingTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0]
                )
            }
    }
    stage("Deploy:") {
        steps {
            echo 'automatic deploy main branch to heroku and docker'
            withCredentials([string(credentialsId: 'T12_ROOTPASS_SECRET', variable: 'rootpass')]) {
                script {
                    def remote = [:]
                    remote.name = 'T12'
                    remote.host = '159.223.45.216'
                    remote.user = 'root'
                    remote.password = "${rootpass}"
                    remote.allowAnyHosts = true
                    sshCommand remote: remote, command: 'git clone https://github.com/Flukena/project-sw-dev-and-env.git'
                    sshCommand remote: remote, command: 'docker-compose -f project-sw-dev-and-env/project_dev-tools_server/docker-compose-deploy-backend.yml up -d'
                }
            }
        }
    }
}
