pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/Flukena/project-sw-dev-and-env.git'
            }
        }
        stage('Download dependency') {
            steps {
                // sh 'cd project_dev-tools_frontend && npm install'
                // sh 'cd project_dev-tools_server && npm install'
                echo 'test'
            }
        }
        stage('Unit test') {
            steps {
                sh 'cd project_dev-tools_frontend && npm run test:unit'
                echo 'Kuy Fluke'
            }
        }
        stage('Test report Unit test') {
            steps {
                echo 'Test report'
            }
        }
        stage('Coverage test report Unit test') {
            steps {
                echo 'Coverage test report'
            }
        }
        stage('Component test') {
            steps {
 		        sh 'cd project_dev-tools_server && npm run start'
                sh 'cd project_dev-tools_frontend && npm run start && npx cypress run'
            }
        }
        stage('Test report Component test') {
            steps {
                echo 'Test report'
            }
        }
        stage('Coverage test report Component test') {
            steps {
                echo 'Coverage test report'
            }
        }
        stage('E2E test') {
            steps {
                echo 'npm run e2e test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
}
