name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [ main ]
  
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: echo 'PORT=${{ secrets.PORT }}' > .env
        
      - name: Run Stop Container
        run: docker kill $(docker ps -q) && docker rmi $(docker images -q)


      - name: Run build      
        run: docker-compose -f "docker-compose.yml" up -d --build
        
