name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [ main ]
  
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: echo 'PORT=${{ secrets.PORT }}' > .env
      
      - name: Run build
        run: docker-compose up -d
        
